made a list of all the reviews
JamesATeasdale/nc-games pull request #1
Opened 2023-04-17 14:50 UTC by JamesATeasdale

2023-04-17 15:05 UTC, callumu21 requested changes
Great start, James! The only thing absolutely missing is:

1. Loading state for your Reviews component. You just need to make sure that your components waiting on fetch requests have some kind of loading state and visual feedback to a user while they are waiting for the request to be completed. I've included a comment below of where this should be.

As for some extra considerations:

1.  I would think about some better semantic HTML choices, as I can begin to see a lot of divs creeping in. Whilst divs are useful for styling and containers, it's important to think about better element choices in our code where possible (e.g. article, section, aside etc.). 
2. Whilst the site isn't having any major issues on smaller screens, give a thought to more responsive design choices, such as the width of your review column on a smaller screen. I appreciate this is something that people like to come back to once the core functionality is up and running, but mobile-first design is definitely the preferred approach for this one.

Once you've added in the loading state, resubmit this PR and we can take another look 👍

2023-04-17 15:05 UTC, callumu21 commented on src/components/Reviews.jsx
> +		fetchReviews().then((data) => setReviews(data));
We should have some loading state here, so that users with slower connections receive some visual feedback that the page is still loading.

2023-04-17 15:05 UTC, callumu21 commented on src/App.js
> +		<body>
We shouldn't have a body element here. This is all returned into the body tags of index.html inside of your public folder so it shouldn't be repeated here as well

2023-04-17 15:05 UTC, callumu21 commented on src/components/Reviews.jsx
> +						<div className="card">
Ideally, we should have a key property here set to a unique value for each review.

2023-04-17 15:05 UTC, callumu21 commented on src/components/api.js
> +import axios from "axios";
Really nice, and good use of a custom instance of Axios 👍

2023-04-18 08:41 UTC, JamesATeasdale commented on src/App.js
> +		<body>
that explains the error i've been getting thanks

2023-04-18 09:58 UTC, merged